[project]
name = "scanalign"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Janne Mareike Koschinski", email = "mail@justjanne.de" }
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "maturin>=1.10.1",
    "mypy>=1.18.2",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "svgelements>=1.9.6",
]

[dependency-groups]
dev = ["pytest>=9.0.1"]

[project.scripts]
scanalign = "scanalign:main"

[build-system]
requires = ["maturin>=1.10,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "scanalign.fcmconv"
