[project]
name = "scanalign"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Janne Mareike Koschinski", email = "mail@justjanne.de" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
]

[dependency-groups]
dev = [
    "hatchling>=1.27.0",
    "pytest>=9.0.1",
]

[project.scripts]
scanalign = "scanalign:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/detect"]
